[project]
name = "mlh-digital-ocean-sf"
version = "0.1.0"
description = "Blender karaoke lyrics animation pipeline"
authors = [
    {name = "robinsonz"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["fake-bpy-module-3-6 (>=20250130,<20250131)"]

[tool.poetry]
packages = [{include = "songs"}]

[tool.poetry.scripts]
preview-lyrics = "songs.words:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
